channels:
- conda-forge
dependencies:
- python=3.12.9
- pip<=24.3.1
- pip:
  - mlflow==3.1.1
  - cloudpickle==3.1.1
  - numpy==2.3.1
  - pandas==2.3.1
  - scikit-learn==1.7.0
  - scipy==1.16.0
name: mlflow-env
